image: java:17
variables:
  DOCKER_DRIVER: overlay
  DOCKER_REPO: mario
  DOCKER_IMAGE: face-engine-backend
  DOCKER_IMAGE_VERSION: v0.5
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - test
  - build
  - package
  - deploy

gradle-test:  # Test job for Gradle
  image: gradle:jdk17  # Using Gradle Docker image
  stage: test
  script:
    - ./gradlew test  # Run Gradle tests
  variables:
    SPRING_DATASOURCE_URL: jdbc:mariadb://198.7.120.11:3306/FACE_ENGINE
    SPRING_DATASOURCE_USERNAME: face_user
    SPRING_DATASOURCE_PASSWORD: face_pass
  artifacts:
    paths:
      - build/test-results/test/  # Ensure this path matches your project structure
      - build/reports/tests/       # Ensure this path matches your project structure

gradle-build:
  image: gradle:jdk17  # Using Gradle Docker image
  stage: build
  script:
    - ./gradlew build  # Run Gradle build
  variables:
    SPRING_DATASOURCE_URL: jdbc:mariadb://198.7.120.11:3306/FACE_ENGINE
    SPRING_DATASOURCE_USERNAME: face_user
    SPRING_DATASOURCE_PASSWORD: face_pass
  artifacts:
    paths:
      - build/libs/*.jar  # Ensure this path matches where your JAR files are located

docker-build:
  stage: package
  script:
    - docker build -t $DOCKER_REPO/$DOCKER_IMAGE:latest .  # Tagging the latest version correctly
    - docker tag $DOCKER_REPO/$DOCKER_IMAGE:latest $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_IMAGE_VERSION  # Tag with version
    - echo $DOCKER_SECRET | docker login -u $DOCKER_USER --password-stdin  # Securely logging in to Docker
    - docker push $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_IMAGE_VERSION  # Push the image with version
